title   : 
subtitle: 
email: 
description: >- # this means to ignore newlines until "baseurl:"
source: ./_src
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # https://example.com/
#livereload: true
# Build settings
#plugins:
#  - jekyll-seo-tag
#  - jekyll-feed
environment: dev
excerpt_separator: <!--more-->

#collections:
#  services:
#    output: true
#  pages:
#    output: true

defaults:
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false
  -
    scope:
      path: "demo.html"
    values:
      sitemap: false
#  - scope:
#      path: ""
#      type: "services"
#    values:
#      layout: "service"
#  - scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
